# Generated by Django 4.2.8 on 2024-08-17 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, unique_for_date="publish"
                    ),
                ),
                (
                    "authors_photo",
                    models.ImageField(blank=True, null=True, upload_to="media"),
                ),
                (
                    "cover_photo",
                    models.ImageField(blank=True, null=True, upload_to="media"),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "blockquote",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="Blockquote"
                    ),
                ),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                ("pinned_post", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("DF", "Draft"), ("PB", "Published")],
                        default="DF",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Posts",
                "ordering": ["-publish"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "comment_photo",
                    models.ImageField(blank=True, null=True, upload_to="media"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("update", models.DateTimeField(auto_now=True, null=True)),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="app.post",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["-publish"], name="app_post_publish_16e00e_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="app_comment_created_ee78ab_idx"
            ),
        ),
    ]
