# Generated by Django 4.2.8 on 2024-01-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_post',
            field=models.BooleanField(default=True),
        ),
    ]
