# Generated by Django 4.2.8 on 2024-08-16 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_post_options_alter_comment_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_photo_one",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_photo_three",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_photo_two",
        ),
    ]
