# Generated by Django 4.2.8 on 2024-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_post_latest_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='authors_photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo_one',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo_three',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_photo_two',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
