# Generated by Django 4.2.8 on 2024-01-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_comment_comment_photo_post_authors_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blockquote',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
