# Generated by Django 4.2.8 on 2024-01-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='latest_post',
            new_name='pinned_post',
        ),
    ]
